apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: {{ template "zookeeper.fullname" . }}
  namespace: {{ $.Release.Namespace }}
spec:
  replicas: 3
  image:
    repository: {{ with .Values.image }}{{ .repository }}{{ end }}
    tag: {{ with .Values.image }}{{ .tag }}{{ end }}
