replicas: 3

image:
  repository: adobe/zookeeper
  tag: 3.6.1
  pullPolicy: IfNotPresent

domainName:
labels: {}
ports: []

pod: {}
  # labels: {}
  # nodeSelector: {}
  # affinity: {}
  # resources: {}
  # tolerations: []
  # env: []
  # annotations: {}
  # securityContext:
  # terminationGracePeriodSeconds: 180

config: {}
  # initLimit: 10
  # tickTime: 2000
  # syncLimit: 2
  # quorumListenOnAllIPs: false

persistence:
  storageClassName: standard
  # specifying reclaim policy for PersistentVolumes
  # accepted values - Delete / Retain
  reclaimPolicy: Delete
  volumeSize: 20Gi

hooks:
  enabled: false
  image:
    repository: lachlanevenson/k8s-kubectl
    tag: v1.16.10
