name: build-publish-docker-image

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - uses: docker/build-push-action@v1
        with:
          dockerfile: Dockerfile
          build_args: VERSION=${{ steps.vars.outputs.tag }},GIT_SHA=${{ github.sha }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: adobe/zookeeper-operator
          tag_with_ref: true
          push: ${{ startsWith(github.ref, 'refs/tags/') }}
      - name: Build and push zookeeper image
        uses: docker/build-push-action@v1
        with:
          path: docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: adobe/zookeeper
          tags: 3.6.2-${{ steps.vars.outputs.tag }}
          add_git_labels: true
